version: '3.4'

services:
  apiload:
    image: ${DOCKER_REGISTRY-}apiload
    build:
      context: .
      dockerfile: APILoad/Dockerfile

  webrazor:
    image: ${DOCKER_REGISTRY-}webrazor
    build:
      context: .
      dockerfile: WebRazor/Dockerfile
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=mydbname2
    volumes:
      - ./volumes1/data/db:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    ports:
       - 5432:5432
    restart: always
    

