version: '3.4'

services:
  apiload:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webrazor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

