version: '3.4'

services:
  apiload:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  webrazor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"

  client:
    ports:
      - "5001:3000"
  
  proxy:
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80" 


