version: '3.4'

services:
  apiload:
    image: ${DOCKER_REGISTRY-}apiload
    build:
      context: .
      dockerfile: APILoad/Dockerfile

  webrazor:
    image: ${DOCKER_REGISTRY-}webrazor
    build:
      context: .
      dockerfile: WebRazor/Dockerfile

  client:
    image: client
    build:
      context: ./my-app
      dockerfile: Dockerfile

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=mydbname2
    volumes:
      - ./volumes1/data/db:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    ports:
       - 5433:5433
    restart: always
    
  proxy:
    image: nginx:mainline
